### ISSUE TITLE
导出笔记内容不全，顺序反了

### ISSUE THREAD

**Issue by pjx1990** [arry-lee/wereader#12]
有些笔记没有全部导出，且导出的章节顺序是反的。

**Comment by jianzhao-yang** [comment]
我也遇到了同样的问题，而且书架上的书显示不出来，只能手段查找bookId

**Comment by callmexss** [comment]
修复了笔记顺序问题，但是内容好像还是不太完整，也没有办法保存想法，提了 pr 还没被合并，可以先试用一下 [https://github.com/callmexss/wereader](https://github.com/callmexss/wereader)
