### ISSUE TITLE
[建议]热门划线按划线人数排序

### ISSUE THREAD

**Issue by qhiuafhdi** [arry-lee/wereader#16]
目前的获取方式是根据划线在书籍中的前后顺序获取，
但有些很少有人划线的内容，看起来没什么价值。

建议按划线人数的多少进行排序，或显示出有”XX人划线“

**Comment by Higurashi-kagome** [comment]
> 目前的获取方式是根据划线在书籍中的前后顺序获取，
> 但有些很少有人划线的内容，看起来没什么价值。
> 
> 建议按划线人数的多少进行排序，或显示出有”XX人划线“

这里实现了显示标注人数，并距有更完善的功能，感兴趣可以试试：[wereader](https://github.com/liuhao326/pythontools/tree/master/wereader)
