### ISSUE TITLE
代码跑起来有点问题，能否抽空帮忙看一下

### ISSUE THREAD

**Issue by wish09** [arry-lee/wereader#18]
报错信息如下：
Traceback (most recent call last):
  File "C:/Users/wish/Desktop/wereader-master/wereader.py", line 168, in <module>
    for b in get_bookshelf():
  File "C:/Users/wish/Desktop/wereader-master/wereader.py", line 132, in get_bookshelf
    if not book['bookId'].isdigit():    # 过滤公众号
KeyError: 'bookId'

自我排查，应该是：
def get_bookshelf(userVid=USERVID):
    """获取书架上所有书"""
    url = "https://i.weread.qq.com/shelf/friendCommon"
这里面的URL链接无法打开的原因，请问下这个链接怎么来的，我找不到目前的替代链接

**Comment by wish09** [comment]
https://i.weread.qq.com/shelf/friendCommon
此链接打开后报-2003错误

**Comment by liuhao326** [comment]
> https://i.weread.qq.com/shelf/friendCommon
> 此链接打开后报-2003错误

这个可能是作者通过手机抓包得到的，可以用https://weread.qq.com/web/shelf试试
