### ISSUE TITLE
如何复制 cookie 的值？

### ISSUE THREAD

**Issue by TrayBer** [arry-lee/wereader#4]
小白求问。

微信扫码登陆后，打开【开发者工具】，在 console 中输入【document.cookie】，三次点击 cookie 值，复制得到的值末尾是省略号，显示不全：
像这样：
ptisp=cnc; vfwebqq=737cb776cba5e1f8c532a9272df0445d287f5eb6a1786ecacfc65337dfeb1f4e738f…"

请问如何复制到完整的 cookie 值啊？

**Comment by arry-lee** [comment]
按Chrome操作如下：
1. F12 开发者工具
2. 点击 Network 
3. 点击 Doc（没有就刷新网页）
4. 点击 Headers 在 RequestHeaders 里复制Cookie

**Comment by arry-lee** [comment]
> 小白求问。
> 
> 微信扫码登陆后，打开【开发者工具】，在 console 中输入【document.cookie】，三次点击 cookie 值，复制得到的值末尾是省略号，显示不全：
> 像这样：
> ptisp=cnc; vfwebqq=737cb776cba5e1f8c532a9272df0445d287f5eb6a1786ecacfc65337dfeb1f4e738f…"
> 
> 请问如何复制到完整的 cookie 值啊？

按Chrome操作如下：

F12 开发者工具
点击 Network
点击 Doc（没有就刷新网页）
点击 Headers 在 RequestHeaders 里复制Cookie

**Comment by TrayBer** [comment]
报错1信息如下：
192:wereader-master Leslie$ python3 /Users/Leslie/Documents/Python/wereader-master/client.py 
Traceback (most recent call last):
  File "/Users/Leslie/Documents/Python/wereader-master/client.py", line 1, in <module>
    from wereader import get_bookshelf,get_chapters,get_bookmarklist,get_bestbookmarks
  File "/Users/Leslie/Documents/Python/wereader-master/wereader.py", line 2, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

好像是提示需要输入，但是控制台窗口并没有提示输入的显示……



报错2信息如下：
192:wereader-master Leslie$ python3 /Users/Leslie/Documents/Python/wereader-master/wereader.py 
Traceback (most recent call last):
  File "/Users/Leslie/Documents/Python/wereader-master/wereader.py", line 2, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

这个不知道错在哪里了？

不懂 Python 编程，网上查找方法并在 macOS 系统安装了 Python3，按照前面的说明获取了 cookie 值，填入了 settings.py 的 cookie 栏中。

作者是否有精力写一个窗口工具或者是一键脚本，感觉这个对非程序员还是很不友好啊，那3个 .py 文件我也不知道先运行哪个，只好一个个试一遍，但都有报错，简直头大……

另外提一个建议：另外开一个 issue 写。

**Comment by arry-lee** [comment]
噢，好像是对不懂python的或非程序员不友好，有时间的话写个工具。
你这个问题是没有安装 requests 模块。pip install requests就好了

**Comment by simple603888** [comment]
copy(document.cookie)
