### ISSUE TITLE
[建议]增加获取豆瓣评分

### ISSUE THREAD

**Issue by TrayBer** [arry-lee/wereader#5]
需求相关信息如下：

**需求缘由：**
微信读书经常送一些网文或者很垃圾的书，因此通过获取豆瓣评分来进行筛选，整理自己的书单列表。

**需求内容：**
获取「微信读书」已购书单列表后，在书籍详情信息中获取 ISBN 值，再通过 ISBN 值获取豆瓣网站的评分。

**Comment by arry-lee** [comment]
书籍详情信息里有评分。
格式如
'ratingCount': 67
ratingDetail': {'one': 10, 'two': 0, 'three': 30, 'four': 160, 'five': 800}}
有需要可自取

**Comment by TrayBer** [comment]
【微信读书】平台内的评分没有参考价值。
就像各个购买电影票的平台对电影的评分也没有参考价值。
如果能够提取ISBN值，自己拿去比较也是不错的。

**Comment by arry-lee** [comment]
确实如此，就是一个豆瓣api就能解决的issue。
