### ISSUE TITLE
[建议]抓取书籍价格

### ISSUE THREAD

**Issue by TrayBer** [arry-lee/wereader#6]
**需求缘由：**
微信读书的所有赠币（可以用来买书）都有使用期限，不使用过期作废，知道书籍价格后，可以及时使用掉快到期的赠送书币。

**需求内容：**
抓取书籍（或者书籍清单、列表）的售价，结合自己的赠币余额购买自己需要的书籍。

**Comment by DavidZhiXing** [comment]
确定吗，哪里有说书币过期

**Comment by zhufree** [comment]
确实会过期，在消费记录里能看到

**Comment by arry-lee** [comment]
get_bookinfo 里面获得的数据有price。
