### ISSUE TITLE
是不是现在已经不能用了啊

### ISSUE THREAD

**Issue by Halfknow** [arry-lee/wereader#8]
微信读书现在已经出了Web版本，我直接输入了自己从cookie中获取的uid，在执行get_bookshelf的时候总是返回请检查网络或cookie设置

**Comment by Halfknow** [comment]
微信读书现在已经出了Web版本，我直接输入了自己从cookie中获取的uid，在执行get_bookshelf的时候总是返回请检查网络或cookie

**Comment by arry-lee** [comment]
最近没测试过，试过完整cookie吗？

**Comment by Halfknow** [comment]
> 最近没测试过，试过完整cookie吗？

试过啦，应该问题是在get_bookshelf执行的时候访问不了了

**Comment by arry-lee** [comment]
我这边测试了，还能使用，没有问题。uid可以不用输入直接enter。
