### ISSUE TITLE
微信公众号的文章列表

### ISSUE THREAD

**Issue by chenluyong** [arry-lee/wereader#9]
作者，感谢您的开源精神，为您的作品点赞。
面对需求来说，微信的文章列表具有一些价值。
通过微信读书可以获取公众号的bookIdList。
希望您能考虑这个思路

**Comment by arry-lee** [comment]
感谢您的pr，我测试过了，公众号只能获取近10篇的标题，链接，没有热门笔记之类，关于公众号的爬虫 github 有其他更专业的项目，本项目中感觉意义不大。
